# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Work
    url: /#features
    weight: 20
  - name: Blog
    url: /#solutions
    weight: 30
  
